- loadbalancer-controller/README.md
Minor fix for loadbalancer controller readme.
Can we use deployment instead of replication controller?
> Fix loadbalancer controller README

- loadbalancer-controller/api/helper.go
- loadbalancer-controller/controller/annotations.go
- loadbalancer-controller/controller/ingress_provision_controller.go
- loadbalancer-controller/controller/utils.go
- loadbalancer-controller/loadbalancerprovider/interface.go
- loadbalancer-controller/loadbalancerprovider/providers/nginx.go
- loadbalancer-controller/main.go
Random comments and typo fix while walking through codebase.
> Add more comments and fix typo

- README.md
- api/types.go
- controller/annotations.go
- controller/loadbalancer_controller.go
- loadbalancerprovider/interface.go
- loadbalancerprovider/providers/nginx.go
- main.go
- Rename ingress_provision_controller to loadbalancer_controller
- Fix a couple of typos
- Add more comments
@mqliang PTAL.  Please make sure the comments are correct; I may have misunderstood some of the code and ingress in general.
> Fix nginx codebase typo and add more comments

- .gitignore
- Makefile
- cmd/controller/main.go
- cmd/controller/options.go
- controller.yaml
- hack/loadbalancer.yaml
- pkg/apis/networking/v1alpha1/types.go
- pkg/util/validation/validation.go
- provider/providers/ipvsdr/ipvsdr.go
- proxy/proxies/nginx/nginx.go
- version/version.go
build: add compile information && update Makefile
fix: podAntiAffinity conflict bug
> Fix: podAntiAffinity conflict bug

- Jenkinsfile
- Makefile
- build/Dockerfile
**What this PR does**
**why we need it**
> ci: update ci tools

- Makefile
**What this PR does**
**why we need it**
> ci: remove dependency in Makefile

- pkg/controller/loadbalancer.go
- pkg/controller/utils.go
**What this PR does**
- fix some typos
- return early for readability
**why we need it**
@zoumo @kdada PTAL.
> Fix typos and return early

- Gopkg.lock
- Gopkg.toml
- Makefile
- pkg/config/config.go
- pkg/provider/providers/ipvsdr/ipvsdr.go
- vendor/github.com/caicloud/clientset/.gitignore
- vendor/github.com/caicloud/clientset/pkg/apis/release/v1alpha1/types.go
**What this PR does**
**why we need it**
> feat: support get node ip from node's labels or annotations

- pkg/provider/providers/external/external.go
- pkg/provider/providers/ipvsdr/ipvsdr.go
- pkg/provider/providers/ipvsdr/status.go
- pkg/provider/providers/providers.go
- pkg/proxy/proxies/nginx/default.go
- pkg/proxy/proxies/nginx/ingress.go
- pkg/util/lb/lb.go
**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:
Fixes #
```release-note
feat(provider): support external provider
```
>  feat(provider): support external provider

- pkg/proxy/proxies/nginx/config.go
**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:
Fixes #
```release-note
feat(nginx): skip nginx status access log
```
> feat(nginx): skip nginx status access log

- pkg/api/well_known.go
- pkg/provider/providers/ipvsdr/ipvsdr.go
- pkg/proxy/proxies/nginx/nginx.go
- pkg/util/lb/lb.go
**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:
Fixes #
```release-note
feat: support static loadbalancer
```
> feat: support static loadbalancer

- pkg/proxy/proxies/nginx/config.go
**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:
Fixes #
```release-note
feat(nginx): merge existing ingress controller config with generated one
```
> feat(nginx): merge existing ingress controller config with generated one

- pkg/proxy/proxies/nginx/ingress.go
Fixes #
Reference to #
```release-note
NONE
```
> feat(nginx): enable ssl passthrough feature

- OWNERS
modify OWNERS
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```
> chore(OWNERS): modify OWNERS

- pkg/proxy/proxies/nginx/nginx.go
Fixes #
Reference to https://github.com/caicloud/quality/issues/863
/cc @li-ang
```release-note
NONE
```
> fix(nginx): nginx should be updated when quota changed

- pkg/provider/providers/external/external.go
- pkg/provider/providers/ipvsdr/ipvsdr.go
- pkg/provider/providers/ipvsdr/status.go
- pkg/proxy/proxies/nginx/nginx.go
- pkg/proxy/proxies/nginx/status.go
Fixes #59 
Reference to #
/cc @li-ang 
```release-note
NONE
```
> fix: clean up legacy and status when spec changed

- pkg/proxy/proxies/nginx/default.go
Fixes #
Reference to #
/cc @liwandaniel 
```release-note
NONE
```
> feat(nginx): move default http backend to kube-system

- release/loadbalancer-controller.yaml
chore(release): add release charts
Fixes #
Reference to #https://github.com/caicloud/pangolin/issues/456
/cc @zoumo 
```release-note
NONE
```
> chore(release): add release charts

- OWNERS
chore(owner): add owner
Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```
> chore(owner): add owner

- release/loadbalancer-controller.yaml
Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```
> chore: use latest tag of caicloud/loadbalancer-provider

- pkg/proxy/proxies/nginx/config.go
Fixes #68 
Reference to #
```release-note
NONE
```
> fix(nginx): replace configmap.Data instead of merging for consistent

- pkg/proxy/proxies/nginx/ingress.go
Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```
> feat(nginx): optimize livenessProbe and args of ingress controller

- pkg/proxy/proxies/nginx/config.go
Fixes #
Reference to #
/cc @whalecold @cd1989 
```release-note
NONE
```
> feat(nginx): set default client max body size to 5GiB

- pkg/provider/providers/azure/azure.go
- release/loadbalancer-controller.yaml
Fixes #
Reference to #
```release-note
NONE
```
> feat(azure): increase terminationGracePeriodSeconds to 300s for azure provider

- release/loadbalancer-controller.yaml
Fixes #
Reference to #
/cc @liwandaniel 
```release-note
NONE
```
> release: update proxy nginx to nginx-ingress-controller:0.23.0

- pkg/provider/providers/ipvsdr/ipvsdr.go
- pkg/proxy/proxies/nginx/ingress.go
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```
> feat: increase resource limits for providers

- pkg/provider/providers/azure/azure.go
- pkg/provider/providers/azure/status.go
fix: set lb unavailable when provider-azure pod can't startup
Fixes #
Reference to #
```release-note
NONE
```
> [CPS-1466] fix: set lb unavailable when provider-azure pod can't startup

- pkg/provider/providers/ipvsdr/status.go
- pkg/proxy/proxies/nginx/status.go
- pkg/util/lb/pod.go
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```
> fix(evict): delete pod if it MatchNodeSelector failed

- LICENSE
- cmd/controller/app/config/config.go
- cmd/controller/app/options/options.go
- hack/license/boilerplate.go.txt
- hack/license/main.go
- pkg/api/well_known.go
- pkg/plugin/builder.go
- pkg/plugin/plugin.go
- pkg/provider/azure/register.go
- pkg/provider/azure/status.go
- pkg/provider/external/external.go
- pkg/provider/external/register.go
- pkg/provider/ipvsdr/register.go
- pkg/proxy/nginx/ingress.go
- pkg/proxy/nginx/register.go
- pkg/util/lb/pod.go
- pkg/util/lb/retry.go
- pkg/version/base.go
- pkg/version/version.go
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```
> fix: correct license tool and license header

- pkg/kubelab/core/interface.go
- pkg/kubelab/factory.go
- pkg/kubelab/meta/interface.go
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```
> fix: import error kubelib -> kubelab

- OWNERS
chore: add owner
Fixes #
Reference to #
```release-note
NONE
```
> chore: add owner

- pkg/provider/providers/azure/azure.go
feat(azure): keep azure provider to listen the app gateway event
Fixes #
Reference to caicloud/service#770
/cc @whalecold @hanxueluo 
```release-note
NONE
```
> feat(azure): keep azure provider to listen the app gateway event

- OWNERS
Fixes #
Reference to #
/cc @whalecold @hicaistar 
```release-note
NONE
```
> chore: OWNERS + hicaistar and sinksmell

- pkg/proxy/nginx/ingress.go
从 Proxy.Spec 中获取 HTTPPort 和 HTTPSPort 启动 ingress 时设置对应的端口号
Fixes #
Reference to #
```release-note
NONE
```
> feat: add http and https port for lb

- pkg/provider/ipvsdr/ipvsdr.go
- pkg/proxy/nginx/ingress.go
- release/loadbalancer-controller.yaml
添加 pod 优先级
Fixes #
Reference to #
/cc @hanxueluo  @hicaistar 
```release-note
NONE
```
> feat: add priority class

- pkg/proxy/nginx/config.go
给 ingress-nginx 的 configMap 添加一个k-v
Fixes #
Reference to #
```release-note
NONE
```
> feat: add server-tokens for configmap

- cmd/controller/app/cmd.go
- cmd/controller/app/options/options.go
提高 lb-controller 命令行参数的兼容性
Fixes #
Reference to #
```release-note
NONE
```
> feat: improve compatibility for CLI args

- pkg/proxy/nginx/config.go
Fixes #
Reference to #
/cc @hicaistar @sinksmell 
```release-note
NONE
```
> fix: keep unrecognized configuration when ensure lb configmap

- Makefile
- cmd/controller/app/cmd.go
- hack/license/main.go
- pkg/config/config.go
- pkg/controller/loadbalancer.go
- pkg/controller/nodes.go
- pkg/kubelab/apps/interface.go
- pkg/kubelab/apps/v1/deployment.go
- pkg/kubelab/core/interface.go
- pkg/kubelab/core/v1/pod.go
- pkg/kubelab/import_known_versions.go
- pkg/kubelab/meta/interface.go
- pkg/provider/azure/azure.go
- pkg/provider/azure/status.go
- pkg/provider/ipvsdr/ipvsdr.go
- pkg/proxy/nginx/config.go
- pkg/proxy/nginx/default.go
- pkg/proxy/nginx/nginx.go
- pkg/toleration/toleration.go
- pkg/util/lb/deployment.go
- pkg/util/lb/event_handler.go
- pkg/util/lb/lb.go
- pkg/util/lb/pod.go
- pkg/util/taints/taints.go
修复 lint 错误
Fixes #
Reference to #
```release-note
NONE
```
> refactor: fix lint code

- pkg/proxy/nginx/config.go
fixup for 2489e648c0a47919f9596c010d3544225b096362
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix(config): proxy-read-timeout is not supported in CPS-2.8 yet

- Makefile
Fixes #
Reference to #
```release-note
NONE
```
> build: sync Makefile from upstream 1f9a3d9

- pkg/provider/ipvsdr/ipvsdr.go
- pkg/proxy/nginx/nginx.go
- pkg/util/lb/deployment.go
Fixes #
Reference to #
/cc @hicaistar @whalecold 
```release-note
NONE
```
> feat(net): add "helm.sh/..." annotation on lb deployment

- pkg/util/lb/deployment.go
Fixes #
Reference to #
```release-note
NONE
```
> fix: add "helm.sh/path" to fixup 3d8b4db

- release/loadbalancer-controller.yaml
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix: not specify priority for none-critical pod on v2.10.0

- pkg/provider/azure/azure.go
- pkg/provider/ipvsdr/ipvsdr.go
- pkg/proxy/nginx/ingress.go
- release/loadbalancer-controller.yaml
Fixes #
Reference to #
```release-note
NONE
```
> fix(net): update controller and provider resources limits and requests

- pkg/controller/nodes.go
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix error reported by golangci-lint v1.20.1

- pkg/provider/azure/azure.go
* feat(azure): keep azure provider to listen the app gateway event
* fix(azure): add clean judgment
Upgrade Project KAIDE from 2.8.3 to 2.9.1
Fixes #
Reference to #
/cc @moshuipan
```release-note
NONE
```
> feat(azure): [KAIDE-54,KAIDE-56,KAIDE-57]CLONE-Upgrade Project KAIDE from 2.8.3 to 2.9.1

- pkg/proxy/nginx/config.go
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> feat: support custom configs for lb

- pkg/proxy/nginx/config.go
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix: only labeled external cm is selected

- pkg/proxy/nginx/ingress.go
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix: set ingress loglevel v=3

- pkg/provider/azure/azure.go
- pkg/provider/ipvsdr/ipvsdr.go
- release/loadbalancer-controller.yaml
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix: increase resource limits and requests

- Gopkg.lock
- Gopkg.toml
- cmd/controller/app/options/options.go
- vendor/github.com/caicloud/clientset/pkg/apis/clever/v1alpha3/types.go
- vendor/github.com/caicloud/go-common/kubernetes/client/client.go
- vendor/github.com/caicloud/go-common/kubernetes/client/doc.go
1. add env "ENV_KUBE_CLIENT_QPS" and "ENV_KUBE_CLIENT_BURST"
2. default value 50 for qps and 100 for burst
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> feat: support qps configuration and add go-common

- Makefile
- build/controller/Dockerfile.arm64
build: support arm64
Fixes #
Reference to #
```release-note
NONE
```
> [CPS-5921] build: support arm64

- pkg/proxy/nginx/ingress.go
- pkg/proxy/nginx/nginx.go
set no default backend service for arm64
Fixes #
Reference to #
```release-note
NONE
```
> feat: set no default backend service for arm64

- pkg/provider/ipvsdr/ipvsdr.go
Fixes #
Reference to #
```release-note
NONE
```
> [CPS-6036]fix: mount xtables file to ipvsdr deployment

- Makefile
Fixes #
Reference to #
```release-note
NONE
```
> upgrade golang version to 1.13.6 & upgrade golangci-lint

- release/loadbalancer-controller.yaml
Fixes #
Reference to #
```release-note
NONE
```
> chore: update nginx-ingress-controller version

- pkg/controller/loadbalancer.go
Fixes #
Reference to #
```release-note
NONE
```
> fix: sync lb crd with the definition in vaquita

- pkg/controller/loadbalancer.go
Fixes #
Reference to #
https://github.com/caicloud/vaquita/pull/745
```release-note
NONE
```
> upgrade crd apiversion to v1 for k8s 1.17+

- pkg/provider/ipvsdr/ipvsdr.go
- pkg/proxy/nginx/nginx.go
- pkg/util/lb/deployment.go
Fixes #
Reference to #
```release-note
NONE
```
> fix: do not add 'helm.sh' annotations on deployment

- pkg/proxy/nginx/config.go
- proxy-read-timeout
- proxy-send-timeout
- upstream-keepalive-timeout
Fixes # http://jira.caicloud.xyz/browse/CPS-6519
Reference to #
```release-note
NONE
```
> feat: clean 3 timeout configuration if not set by CPS lb

- go.mod
- go.sum
- vendor/github.com/caicloud/go-common/kubernetes/leaderelection/leaderelection.go
- vendor/modules.txt
Fixes #
Reference to #
```release-note
NONE
```
> fix: upgrade go-common=0.3.6

- pkg/provider/azure/azure.go
[KAIDE-54,KAIDE-56,KAIDE-57]CLONE-Upgrade Project KAIDE from 2.8.3 to 2.9.1 (#132)
(cherry picked from commit 3a71c81485dde42a6a558791296b851849e83b2b)
Fixes #
Reference to #
```release-note
NONE
```
> feat(appgateway): use azure app-gateway as provider

- pkg/controller/loadbalancer.go
- pkg/provider/azure/azure.go
fix http://jira.caicloud.xyz/browse/KAIDE-119
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix(appgateway): handle lb azure annotation change

- cmd/controller/main.go
- go.mod
- go.sum
- vendor/github.com/caicloud/go-common/signal/stopsignal.go
- vendor/github.com/caicloud/go-common/signal/stopsignal_posix.go
- vendor/github.com/caicloud/go-common/signal/stopsignal_windows.go
- vendor/modules.txt
主进程异常退出，而 leaderelection 未退出，进入“假活” 状态，从 pod 看是 running 状态，而不能提供服务。
Fixes #
Reference to #
```release-note
NONE
```
> [CPS-7306]fix: false live state caused by leaderelection

- pkg/proxy/nginx/config.go
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix: fix broken custom lb config caused by eb249d69

- release/loadbalancer-controller.yaml
Fixes #
Reference to #
/cc @hicaistar
```release-note
NONE
```
> fix(resource): increate limits and requests

- release/loadbalancer-controller.yaml
Fixes #
Reference to #
/cc @hanxueluo @hicaistar
```release-note
NONE
```
> chore(nginx): bump up ingress-nginx version

- pkg/provider/ipvsdr/ipvsdr.go
- pkg/proxy/nginx/nginx.go
We should not return notFound error in cleanup. Otherwise, it may cause following error:
"k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Pod: Get https://10.254.0.1:443/api/v1/pods?limit=500&resourceVersion=0: http2: no cached connection was available"
clean up 里不应该返回 not found 的错误，当不存在 ipvsdr provider 和 nginx deployment 时，不应该返回 error，阻塞 sync queue
解决 error: 
"ERROR: logging before flag.Parse: E0712 15:02:05.994663       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.Pod: Get https://10.254.0.1:443/api/v1/pods?limit=500&resourceVersion=0: http2: no cached connection was available"
Fixes #
Reference to #
**Special notes for …
> fix(kong): ignore not found error in cleanup

- pkg/proxy/nginx/config.go
nginx is behind f5 L7 loadbalancer,so:
ref:
> use-forwarded-headers
> If true, NGINX passes the incoming X-Forwarded-* headers to upstreams. Use this option when NGINX is behind another L7 proxy / load balancer that is setting these headers.
>
> If false, NGINX ignores incoming X-Forwarded-* headers, filling them with the request information it sees. Use this option if NGINX is exposed directly to the internet, or it's behind a L3/packet-based load balancer that doesn't alter the source IP in the packets.
Fixes #
Reference to #
```release-note
NONE
```
> feat: set use-forwarded-header to true as default config

- OWNERS
Fixes #
Reference to #
```release-note
NONE
```
> chore(owners): add approver and reviewer VincentGuoCQ

- pkg/proxy/nginx/ingress.go
- pkg/proxy/nginx/nginx.go
Fixes # http://jira.caicloud.xyz/browse/CPS-7327
Reference to #
```release-note
NONE
```
> feat(ingress): remove nginx proxy sidecar

- Makefile
Automatically submit by tool file-sync, author by @bbbmj
/cc
```release-note
NONE
```
> feat(*): upgrade golang image to 1.13-security

- Makefile
Fixes #
Reference to # http://jira.caicloud.xyz/browse/CPS-8648
```release-note
NONE
```
> feat(*): upgrade golang image to 1.12-security

- pkg/proxy/kong/kong.go
- pkg/proxy/nginx/nginx.go
- 更新 LB 信息导致 Ingress 被删除
Fixes #
Reference to #
```release-note
NONE
```
> fix(sunny): modify LB results in ingress rule deletion
